http:
  port: "8081"
  
sfdc:
  username: "vineela@mulesoft.com"
  password: "mulesoft@123"
  token: "8hN7lM7Mhv6Lhb88TPLdbwCMA"
  
file: 
  accountsDir: "C:/Users/lkgud/OneDrive/Desktop/MuleSoft_Fundamentals/APDevFundamentals4.3_studentFiles_29apr2021/resources"

db:
  host: "iltdb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"